// demo/next/app/about/page.tsx
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'About | AEO Demo Site',
  description: 'Learn more about the AEO Demo Site and the aeo.js library.',
};

export default function AboutPage() {
  return (
    <>
      <h1>About</h1>
      <p>
        The AEO Demo Site is a sample project built to demonstrate how <strong>aeo.js</strong> works
        with Next.js. AEO (Answer Engine Optimization) helps your site surface better
        in AI-powered search engines and answer engines.
      </p>
      <p>
        This project uses the Next.js App Router with server components and integrates
        aeo.js via the <code>withAeo</code> Next.js plugin to automatically inject
        structured data and metadata across all pages.
      </p>
    </>
  );
}

// demo/nuxt/pages/about.vue
<template>
  <div>
    <Head>
      <title>About - AEO Demo</title>
      <meta name="description" content="Learn more about the AEO.js demo project." />
    </Head>
    <h1>About</h1>
    <p>
      AEO.js is a lightweight library that helps websites become more visible to
      AI-powered answer engines. It works by enriching your pages with structured
      data, semantic HTML hints, and machine-readable metadata.
    </p>
    <p>
      This demo site is built with Nuxt 3 and uses the official aeo.js Nuxt
      module. The module scans your routes at build time and injects the
      appropriate tags automatically — no manual configuration needed per page.
    </p>
  </div>
</template>
