// demo/next/app/products/page.tsx
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Products | AEO Demo Site',
  description: 'Explore our demo product catalog powered by aeo.js.',
};

const products = [
  { name: 'Widget Alpha', description: 'A versatile widget for everyday use.' },
  { name: 'Widget Beta', description: 'An advanced widget with premium features.' },
  { name: 'Widget Gamma', description: 'A lightweight widget optimized for speed.' },
  { name: 'Widget Delta', description: 'A heavy-duty widget built for enterprise scale.' },
];

export default function ProductsPage() {
  return (
    <>
      <h1>Products</h1>
      <p>Browse our catalog of demo products below.</p>
      <ul>
        {products.map((product) => (
          <li key={product.name}>
            <h2>{product.name}</h2>
            <p>{product.description}</p>
          </li>
        ))}
      </ul>
    </>
  );
}

// demo/nuxt/pages/products.vue
<template>
  <div>
    <Head>
      <title>Products - AEO Demo</title>
      <meta name="description" content="Browse the products available in the AEO.js demo store." />
    </Head>
    <h1>Products</h1>
    <p>Below is a sample list of products to demonstrate list-style page content.</p>
    <ul>
      <li><strong>Widget Alpha</strong> — A versatile widget for everyday tasks. $9.99</li>
      <li><strong>Widget Beta</strong> — An upgraded widget with extended features. $19.99</li>
      <li><strong>Widget Gamma</strong> — The premium widget for power users. $29.99</li>
      <li><strong>Accessory Pack</strong> — Essential add-ons for any widget. $4.99</li>
    </ul>
  </div>
</template>
