// demo/nuxt/pages/contact.vue
<template>
  <div>
    <Head>
      <title>Contact - AEO Demo</title>
      <meta name="description" content="Get in touch with the AEO.js demo team." />
    </Head>
    <h1>Contact</h1>
    <p>
      Have questions about aeo.js? We would love to hear from you. Reach out
      through any of the channels below.
    </p>
    <ul>
      <li>Email: hello@aeojs.org</li>
      <li>GitHub: github.com/multivmlabs/aeojs</li>
      <li>Twitter: @aeojs</li>
    </ul>
  </div>
</template>

// demo/next/app/contact/page.tsx
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Contact | AEO Demo Site',
  description: 'Get in touch with us.',
};

export default function ContactPage() {
  return (
    <>
      <h1>Contact</h1>
      <p>
        Have questions about aeo.js or this demo? We would love to hear from you.
      </p>
      <p>
        <strong>Email:</strong> hello@aeojs.org
      </p>
      <p>
        <strong>GitHub:</strong>{' '}
        <a href="https://github.com/multivmlabs/aeojs" target="_blank" rel="noopener noreferrer">
          multivmlabs/aeojs
        </a>
      </p>
    </>
  );
}
