// demo/vite-react/src/pages/Contact.tsx
function Contact() {
  return (
    <div>
      <h1>Contact</h1>
      <p>
        Have questions about aeo.js? We would love to hear from you.
      </p>
      <p>
        Email: <a href="mailto:hello@aeojs.org">hello@aeojs.org</a>
      </p>
      <p>
        GitHub: <a href="https://github.com/multivmlabs/aeojs" target="_blank" rel="noopener noreferrer">multivmlabs/aeojs</a>
      </p>
    </div>
  );
}

export default Contact;

// demo/angular/src/app/contact/contact.component.ts
import { Component, ChangeDetectionStrategy } from '@angular/core';

@Component({
  selector: 'app-contact',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <h1>Contact Us</h1>
    <p>
      Have questions about aeo.js or need help with your integration? We would love to hear
      from you.
    </p>
    <p>
      <strong>Email:</strong> hello&#64;aeojs.org
    </p>
    <p>
      <strong>GitHub:</strong> github.com/multivmlabs/aeojs
    </p>
    <p>
      <strong>Documentation:</strong> docs.aeojs.org
    </p>
  `,
})
export class ContactComponent {}
